

// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// USER ACTIONS
export const CREATE_USER = 'CREATE_USER';
export const FETCH_USER = 'FETCH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// LAST.FM API ACTIONS
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FAVORITE_ARTIST_SUCCESS = 'FAVORITE_ARTIST_SUCCESS';
export const FETCH_FAVORITE_ARTISTS = 'FETCH_FAVORITE_ARTISTS';
export const FAVORITE_TRACK_SUCCESS = 'FAVORITE_TRACK_SUCCESS';

// DASHBOARD ACTIONS
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const VIEW_USER = 'VIEW_USER';
export const UNSELECT_USER = 'UNSELECT_USER';
